version: "3"
services:
  node-app:
    build:
      context: ./node-app/
    volumes:
      - ./node-app:/root
    tty: true
    stdin_open: true

  browser-app:
    build:
      context: ./browser-app/
    container_name: browser-app
    command: "npm run serve"
    volumes:
      - ./browser-app:/root
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

  react-app:
    build:
      context: ./react-app/
    container_name: react-app
    #command: "npm run serve"
    volumes:
      - ./react-app:/root
    ports:
      - 3001:3000
    tty: true
    stdin_open: true
