version: "3"
services:
  node-app:
    build:
      context: ./node-app/
    volumes:
      - ./node-app:/root
    tty: true
    stdin_open: true

  browser-app:
    build:
      context: ./browser-app/
    container_name: browser-app
    command: "bash -c 'npm run build && npm run serve'"
    volumes:
      - ./browser-app:/root
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
